# Generated by Django 5.2.4 on 2025-07-10 08:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Номер телефона в формате +7XXXXXXXXXX', max_length=15, null=True, verbose_name='Номер телефона')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация о пользователе (до 500 символов)', max_length=500, null=True, verbose_name='О себе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(help_text='Связанный пользователь Django', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя человека, отправившего сообщение', max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Имя должно содержать минимум 2 символа')], verbose_name='Имя отправителя')),
                ('email', models.EmailField(help_text='Электронная почта для обратной связи', max_length=254, verbose_name='Email отправителя')),
                ('message_text', models.TextField(help_text='Содержание сообщения (до 500 символов)', validators=[django.core.validators.MinLengthValidator(10, 'Сообщение должно содержать минимум 10 символов'), django.core.validators.MaxLengthValidator(500, 'Сообщение не должно превышать 500 символов')], verbose_name='Текст сообщения')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-адрес отправителя сообщения', null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('is_read', models.BooleanField(default=False, help_text='Отметка о том, что сообщение было прочитано администратором', verbose_name='Прочитано')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, отправивший сообщение (если авторизован)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='forms_app_m_is_read_80a0c8_idx'), models.Index(fields=['user', '-created_at'], name='forms_app_m_user_id_3db838_idx')],
            },
        ),
    ]
